

// Giscus Configuration (get values from https://giscus.app)
export const GISCUS_CONFIG = {
  repo: 'soft-zihan/soft-zihan.github.io',
  repoId: 'R_kgDOQ1b8-A',
  category: 'Announcements',
  categoryId: 'DIC_kwDOQ1b8-M4C1Ezk'
}

// Umami Configuration (optional)
export const UMAMI_CONFIG = {
  websiteId: '', // Fill from Umami dashboard
  scriptUrl: 'https://cloud.umami.is/script.js'
}

export const I18N = {
  en: {
    loading: "Loading Sakura Notes...",
    subtitle: "For every reader",
    tab_latest: "Latest",
    tab_files: "Files",
    tab_lab: "Laboratory",
    lab_dashboard: "Visual Learning Center",
    lab_dashboard_desc: "Front-end magic",
    lab_tools: "Visual Playground",
    lab_resources: "Learning Resources",
    lab_course: "Vue Ninja Training (Project Based)",
    
    // New v1.1 strings
    search_title: "Search Notes",
    search_no_results: "No results found",
    search_try_different: "Try different keywords",
    music_player: "Music Player",
    music_playlist: "Playlist",
    music_request: "Request a song",
    music_no_tracks: "No tracks",
    write_title: "Writing Studio",
    write_publish: "Publish to GitHub",
    write_draft: "Save Draft",
    write_token_config: "Configure GitHub Token",
    comments_title: "Comments",
    banner_settings: "Background Settings",
    banner_normal: "Normal",
    banner_fullscreen: "Fullscreen",
    banner_background: "Background",
    banner_hide: "Hide",
    like: "Like",
    favorite: "Favorite",
    share: "Share",
    
    // Categories
    cat_foundation: "Web Foundation",
    cat_vue: "Vue Core",
    cat_network: "Network & Async",
    cat_challenge: "Challenge",

    // Web Standards Tool
    lab_standards_title: "The Web Standards Triad",
    lab_standards_desc: "Understanding the role of HTML, CSS, and JavaScript based on W3C standards.",
    lab_st_html: "HTML (Structure)",
    lab_st_css: "CSS (Presentation)",
    lab_st_js: "JS (Behavior)",
    lab_st_info_html: "HTML is the skeleton. It defines WHAT is on the page.",
    lab_st_info_css: "CSS is the skin/clothing. It defines HOW it looks.",
    lab_st_info_js: "JS is the muscle/soul. It defines HOW it interacts.",

    // HTML/JS Tools
    lab_html_title: "HTML Parser & Tokenizer",
    lab_html_info: "See how the browser engine breaks down raw text into Tokens and builds the DOM Tree.",
    lab_html_mode: "Mode",
    lab_html_debug: "Tree View",
    lab_html_preview: "Render View",
    lab_html_tokens: "Token Stream",
    lab_html_tree: "Constructed DOM Tree",
    
    // JS Lab (Updated)
    lab_js_title: "JS Runtime Sandbox",
    lab_js_tab_basics: "Runtime REPL",
    lab_js_tab_coercion: "Type Coercion Matrix",
    lab_js_run: "Run Code",
    lab_js_result: "Result",
    lab_js_console: "Console Output",
    lab_js_info: "Type real JavaScript code. Variables are scoped to this sandbox.",

    // DOM Lab
    lab_dom_title: "DOM Manipulation Playground",
    lab_dom_desc: "Interact with page elements using standard DOM APIs.",
    lab_dom_target: "Target Element",
    lab_dom_action: "Execute JS",
    lab_dom_console: "Console Output",
    lab_dom_btn_text: "Change Text",
    lab_dom_btn_color: "Change Color",
    lab_dom_btn_hide: "Hide Element",
    lab_dom_btn_show: "Show Element",

    // Ajax Lab
    lab_ajax_title: "Async Interaction (Province/City)",
    lab_ajax_desc: "Simulating the Province-City-Area selection flow from the course.",
    lab_ajax_sync: "Promise Chain (.then)",
    lab_ajax_async: "Async / Await",
    lab_ajax_step_1: "1. Request Province",
    lab_ajax_step_2: "2. Request City (pid=)",
    lab_ajax_step_3: "3. Request Area (cid=)",
    lab_ajax_complete: "Data Loaded!",
    lab_ajax_start: "Start Request",
    lab_ajax_reset: "Reset",

    // Vue List Lab
    lab_vue_list_title: "Employee Management (v-for/v-if)",
    lab_vue_list_desc: "Rendering a list based on raw data with conditional formatting.",
    lab_vue_form_name: "Name",
    lab_vue_form_gender: "Gender",
    lab_vue_form_job: "Job",
    lab_vue_add: "Add Employee",
    lab_vue_empty: "No data available",
    lab_vue_view_ui: "👁️ View UI",
    lab_vue_view_code: "📝 View Source",
    lab_gender_1: "Male",
    lab_gender_2: "Female",
    lab_job_1: "Lecturer",
    lab_job_2: "Teacher",
    lab_job_3: "Other",
    
    // Existing Vue Tools
    lab_reactivity: "Reactivity Core",
    lab_reactivity_desc: "Visualizing Track & Trigger",
    lab_reactivity_track: "Track (Get)",
    lab_reactivity_trigger: "Trigger (Set)",
    lab_reactivity_deps: "Dependency Bucket (Dep)",
    lab_reactivity_effect: "Active Effect",
    lab_lifecycle: "Lifecycle",
    lab_lifecycle_desc: "Hook execution flow",
    lab_lifecycle_component: "Virtual Component",
    lab_lifecycle_state: "State",
    lab_directives: "Directives",
    lab_directives_desc: "v-if vs v-show visualizer",
    lab_quiz: "Vue Ninja Quiz",
    lab_quiz_desc: "Test your knowledge!",

    // Class & Style Lab (NEW)
    lab_class_title: "Class & Style Binding",
    lab_class_desc: "Master the object and array syntax for dynamic styling.",
    lab_class_toggle: "Toggle Class",
    lab_class_style_ctrl: "Style Controls",
    lab_class_result: "Rendered Element",
    lab_class_code: "Generated Data",
    lab_class_info: "Manipulate the controls to see how Vue updates the class list and inline styles.",

    // Props & Emit Lab
    lab_props_title: "Component Communication",
    lab_props_desc: "Visualizing One-Way Data Flow.",
    lab_props_parent: "Parent (Controller)",
    lab_props_child: "Child (Robot)",
    lab_props_msg: "Message",
    lab_props_status: "Status",
    lab_props_emit_log: "Event Log (from Child)",
    lab_props_action_hit: "Hit",
    lab_props_action_heal: "Heal",
    lab_props_info: "Props pass data DOWN. Events emit UP.",
    
    // Quiz Extended
    quiz_cat_all: "Mixed Challenge",
    quiz_cat_basic: "HTML & CSS",
    quiz_cat_js: "JavaScript Core",
    quiz_cat_vue: "Vue.js Ecology",
    quiz_streak: "Streak",
    quiz_score: "Score",
    quiz_lifeline_5050: "50/50",
    quiz_lifeline_used: "Used",
    quiz_review: "Review Mistakes",
    quiz_explanation: "Explanation",
    quiz_perfect: "Perfect! You are a master!",
    quiz_good: "Great job! Keep practicing.",
    quiz_try: "Don't give up! Review the notes.",

    // Code Evolution Lab (NEW)
    evo_title: "From Zero to Vue: The Evolution",
    evo_desc: "Watch how a simple counter evolves from static HTML to a modern Vue app. Each step solves a real problem.",
    evo_stage_html: "Structure Only",
    evo_stage_css: "Add Styling",
    evo_stage_js: "Add Behavior",
    evo_stage_vue: "Modern Framework",
    evo_what_changed: "- What Changed?",
    evo_problem_solved: "Problem Solved",
    evo_summary: "Learning Path",
    evo_html_note: "Static! Buttons don't work.",
    evo_css_note: "Beautiful! But still static.",
    evo_js_note: "Try clicking the buttons!",
    evo_vue_note: "Reactive! Data drives UI automatically.",
    evo_even: "Even",
    evo_odd: "Odd",
    evo_positive: "Positive",
    evo_negative: "Negative",
    
    // Resources Categories
    res_cat_platform: "Interactive Platforms",
    res_cat_frontend_games: "Frontend Games",
    res_cat_vue_projects: "Vue Mini Projects",

    // General
    no_notes: "No notes found in 'en' folder.",
    no_vue_notes: "Course notes folder not found.",
    reading_notes: "Reading notes...",
    welcome_title: "Welcome Home",
    welcome_desc: "Explore the garden of knowledge belongs to you",
    welcome_tags: "Share Notes · Learn Vue",
    on_this_page: "On this page",
    note_details: "Note Details",
    words: "Words",
    lines: "Lines",
    format: "Format",
    updated: "Updated",
    settings_title: "Settings",
    font_style: "Font Style",
    font_size: "Font Size",
    sakura_speed: "Sakura Speed",
    speed_5cm: "5cm/s (Slow)",
    speed_10cm: "10cm/s (Fast)",
    theme: "Theme",
    theme_light: "Light",
    theme_dark: "Dark",
    done: "Done",
    close: "Close",
    link_copied: "Link copied! 🌸",
    copy_link: "Copy Link",
    view_source: "View Source",
    view_render: "View Render",
    download: "Download",
    search_placeholder: "Search notes...",
    back_home: "Home",
    toast_copied: "Copied to clipboard!",
    copied: "Copied!",
    file_not_found: "File not found",
    menu_highlight: "Highlight",
    menu_underline: "Underline",
    selection_error: "Selection cannot cross paragraphs.",
    
    // Lab Components content
    lab_reactivity_title: "Reactivity System: Track & Trigger",
    lab_reactivity_info: "Visualize how Vue collects dependencies (Track) into a Bucket and re-runs effects (Trigger) when data changes.",
    lab_lifecycle_title: "Lifecycle Coaster",
    lab_lifecycle_btn_mount: "Mount",
    lab_lifecycle_btn_update: "Update",
    lab_lifecycle_btn_unmount: "Unmount",
    lab_directives_title: "Directives: v-if vs v-show",
    lab_directives_info: "Visualizing how Vue handles conditional rendering and DOM updates.",
    lab_quiz_start: "Start Training",
    lab_quiz_title: "Vue Ninja Training",
    lab_quiz_subtitle: "Test your reflexes and Vue knowledge based on the course.",
    res_vue_mastery_desc: "Gamified learning path",
    res_scrimba_desc: "Interactive video tutorials"
  },
  zh: {
    loading: "正在加载樱花笔记...",
    subtitle: "献给所有读者",
    tab_latest: "最新",
    tab_files: "归档",
    tab_lab: "实验室",
    lab_dashboard: "可视化学习中心",
    lab_dashboard_desc: "前端魔法",
    lab_tools: "交互演示",
    lab_resources: "前端修炼场",
    lab_course: "Vue 实战笔记 (源码解析)",

    // New v1.1 strings
    search_title: "搜索笔记",
    search_no_results: "未找到相关结果",
    search_try_different: "试试其他关键词",
    music_player: "音乐播放器",
    music_playlist: "播放列表",
    music_request: "点歌",
    music_no_tracks: "暂无歌曲",
    write_title: "写作工作台",
    write_publish: "发布到 GitHub",
    write_draft: "保存草稿",
    write_token_config: "配置 GitHub Token",
    comments_title: "评论区",
    banner_settings: "背景设置",
    banner_normal: "正常",
    banner_fullscreen: "全屏",
    banner_background: "背景",
    banner_hide: "隐藏",
    like: "点赞",
    favorite: "收藏",
    share: "分享",

    // Categories
    cat_foundation: "Web 基础 (JS/DOM)",
    cat_vue: "Vue 核心",
    cat_network: "网络与异步",
    cat_challenge: "挑战",

    // Web Standards Tool
    lab_standards_title: "Web 标准三剑客",
    lab_standards_desc: "基于 W3C 标准，直观理解 HTML、CSS 和 JavaScript 的分工。",
    lab_st_html: "HTML (结构)",
    lab_st_css: "CSS (表现)",
    lab_st_js: "JS (行为)",
    lab_st_info_html: "HTML 是骨架。它定义了页面上“有什么” (What)。",
    lab_st_info_css: "CSS 是皮肤/衣服。它定义了页面“长什么样” (How Look)。",
    lab_st_info_js: "JS 是肌肉/灵魂。它定义了页面“怎么动” (How Act)。",

    // HTML/JS Tools
    lab_html_title: "HTML 词法分析与 DOM 构建",
    lab_html_info: "输入代码，实时观察浏览器如何将字符流拆解为 Token，并构建出 DOM 树结构。",
    lab_html_mode: "视图模式",
    lab_html_debug: "DOM 树状图",
    lab_html_preview: "真实渲染",
    lab_html_tokens: "Token 流 (词法分析)",
    lab_html_tree: "DOM 树 (语法分析)",

    // JS Lab (Updated)
    lab_js_title: "JS 运行时沙箱",
    lab_js_tab_basics: "REPL (执行环境)",
    lab_js_tab_coercion: "类型转换矩阵",
    lab_js_run: "执行代码",
    lab_js_result: "执行结果",
    lab_js_console: "控制台输出",
    lab_js_info: "在这里编写真实的 JavaScript 代码。变量仅在当前沙箱内有效。",
    lab_js_log: "事件日志",
    lab_js_clear: "清空",

    // DOM Lab
    lab_dom_title: "DOM 操作演练场",
    lab_dom_desc: "使用标准的 document API 操作页面元素。",
    lab_dom_target: "目标元素",
    lab_dom_action: "执行 JS 代码",
    lab_dom_console: "控制台输出",
    lab_dom_btn_text: "修改内容 (innerHTML)",
    lab_dom_btn_color: "修改颜色 (Style)",
    lab_dom_btn_hide: "隐藏元素 (Display)",
    lab_dom_btn_show: "显示元素 (Display)",

    // Ajax Lab
    lab_ajax_title: "异步交互 (省市区联动)",
    lab_ajax_desc: "模拟课程中的“省-市-区”三级联动请求流程。",
    lab_ajax_sync: "链式调用 (.then)",
    lab_ajax_async: "Async / Await",
    lab_ajax_step_1: "1. 请求省份 (Province)",
    lab_ajax_step_2: "2. 请求城市 (City)",
    lab_ajax_step_3: "3. 请求区县 (Area)",
    lab_ajax_complete: "数据加载完成！",
    lab_ajax_start: "发起请求",
    lab_ajax_reset: "重置",

    // Vue List Lab (Updated)
    lab_vue_list_title: "员工管理系统 (v-for/v-if)",
    lab_vue_list_desc: "复刻课程案例：根据原始数据渲染表格，处理性别与职位的显示逻辑。",
    lab_vue_form_name: "姓名",
    lab_vue_form_gender: "性别",
    lab_vue_form_job: "职位",
    lab_vue_add: "入职 (添加)",
    lab_vue_empty: "暂无数据",
    lab_vue_view_ui: "👁️ 查看界面",
    lab_vue_view_code: "📝 查看源码",
    lab_gender_1: "男",
    lab_gender_2: "女",
    lab_job_1: "讲师",
    lab_job_2: "班主任",
    lab_job_3: "其他",

    // Existing Vue Tools
    lab_reactivity: "响应式原理 (Core)",
    lab_reactivity_desc: "可视化 Track 与 Trigger",
    lab_reactivity_track: "收集依赖 (Track)",
    lab_reactivity_trigger: "触发更新 (Trigger)",
    lab_reactivity_deps: "依赖桶 (Dep Set)",
    lab_reactivity_effect: "副作用 (ActiveEffect)",
    lab_lifecycle: "生命周期",
    lab_lifecycle_desc: "钩子执行流程",
    lab_lifecycle_component: "虚拟组件",
    lab_lifecycle_state: "状态",
    lab_directives: "指令实验室",
    lab_directives_desc: "v-if 与 v-show 的区别",
    lab_quiz: "Vue 忍者挑战",
    lab_quiz_desc: "基于课程内容的随机测试！",

    // Class & Style Lab (NEW)
    lab_class_title: "Class 与 Style 绑定",
    lab_class_desc: "掌握 Vue 中处理动态样式的对象语法与数组语法。",
    lab_class_toggle: "切换 Class",
    lab_class_style_ctrl: "Style 控制",
    lab_class_result: "渲染结果",
    lab_class_code: "数据源",
    lab_class_info: "操作下方的开关，观察 Vue 如何动态生成 class 字符串和 style 对象。",

    // Props & Emit Lab
    lab_props_title: "组件通信 (Props & Emit)",
    lab_props_desc: "可视化单向数据流与事件冒泡。",
    lab_props_parent: "父组件 (控制器)",
    lab_props_child: "子组件 (机器人)",
    lab_props_msg: "指令消息",
    lab_props_status: "运行状态",
    lab_props_emit_log: "事件日志 (来自子组件)",
    lab_props_action_hit: "受击",
    lab_props_action_heal: "治疗",
    lab_props_info: "Props 数据向下流，Emit 事件向上冒。",
    
    // Quiz Extended
    quiz_cat_all: "综合大挑战",
    quiz_cat_basic: "HTML & CSS 基础",
    quiz_cat_js: "JavaScript 核心",
    quiz_cat_vue: "Vue.js 全家桶",
    quiz_streak: "连胜",
    quiz_score: "得分",
    quiz_lifeline_5050: "50/50 排除",
    quiz_lifeline_used: "已使用",
    quiz_review: "错题回顾",
    quiz_explanation: "解析",
    quiz_perfect: "太强了！你已经掌握了所有课程内容！",
    quiz_good: "干得漂亮！继续复习 source-2.md。",
    quiz_try: "别灰心！回顾一下 source-1.md 再来。",

    // Code Evolution Lab (NEW)
    evo_title: "从零到 Vue：代码演进之旅",
    evo_desc: "观察一个简单的计数器如何从静态 HTML 演进为现代 Vue 应用。每一步都在解决真实问题。",
    evo_stage_html: "仅结构",
    evo_stage_css: "添加样式",
    evo_stage_js: "添加行为",
    evo_stage_vue: "现代框架",
    evo_what_changed: "- 发生了什么？",
    evo_problem_solved: "解决了什么问题",
    evo_summary: "学习路径",
    evo_html_note: "静态的！按钮没反应。",
    evo_css_note: "好看了！但还是静态的。",
    evo_js_note: "试试点击按钮！",
    evo_vue_note: "响应式！数据自动驱动 UI 更新。",
    evo_even: "偶数",
    evo_odd: "奇数",
    evo_positive: "正数",
    evo_negative: "负数",

    // Resources Categories
    res_cat_platform: "互动学习平台",
    res_cat_frontend_games: "前端游戏化学习",
    res_cat_vue_projects: "Vue 实战项目",

    // General
    no_notes: "在 'zh' 文件夹下暂无笔记",
    no_vue_notes: "未找到 'VUE学习笔记' 文件夹",
    reading_notes: "读取笔记中...",
    welcome_title: "欢迎回家",
    welcome_desc: "探索属于你的知识花园",
    welcome_tags: "分享笔记 · Vue 学习",
    on_this_page: "目录",
    note_details: "笔记详情",
    words: "字数",
    lines: "行数",
    format: "格式",
    updated: "最后更新",
    settings_title: "用户设置",
    font_style: "字体风格",
    font_size: "字体大小",
    sakura_speed: "花落速度",
    speed_5cm: "秒速五厘米 (唯美)",
    speed_10cm: "秒速十厘米 (轻快)",
    theme: "主题模式",
    theme_light: "浅色",
    theme_dark: "深色",
    done: "完成",
    close: "关闭",
    link_copied: "链接已复制! 🌸",
    copy_link: "复制链接",
    view_source: "查看源码",
    view_render: "查看渲染",
    download: "下载",
    search_placeholder: "搜索笔记...",
    back_home: "首页",
    toast_copied: "已复制到剪贴板！",
    copied: "已复制！",
    file_not_found: "文件未找到",
    menu_highlight: "高亮",
    menu_underline: "波浪线",
    selection_error: "无法跨段落标注",
    
    // Lab Components content
    lab_reactivity_title: "响应式系统: 依赖收集与触发",
    lab_reactivity_info: "深入 Vue 3 原理：观察读取数据时如何收集依赖 (Track)，以及修改数据时如何从依赖桶中取出并执行更新 (Trigger)。",
    lab_lifecycle_title: "生命周期过山车",
    lab_lifecycle_btn_mount: "挂载 (Mount)",
    lab_lifecycle_btn_update: "更新 (Update)",
    lab_lifecycle_btn_unmount: "卸载 (Unmount)",
    lab_directives_title: "指令对比: v-if vs v-show",
    lab_directives_info: "可视化 Vue 如何处理条件渲染和 DOM 更新。",
    lab_quiz_start: "开始修炼",
    lab_quiz_title: "Vue 忍者训练",
    lab_quiz_subtitle: "测试你的反应速度和 Vue 知识 (基于课程标准)。",
    res_vue_mastery_desc: "游戏化学习路径",
    res_scrimba_desc: "交互式视频教程"
  }
};